version: '3.8'

services:
  ble-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    working_dir: /workspace
    command: sleep infinity
